name: DevOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Log errors if tests fail"
        required: true
        default: "false"

env:
  DOCKER_IMAGE_NAME: emmynaessrieback/devops_project_emmy
  SMHI_API_KEY: ${{ secrets.SMHI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: test_step
        run: |
          python -m unittest discover -s tests || echo "Tests failed"
        if: ${{ github.event.inputs.log_errors != 'true' }}

      - name: Upload error log if tests fail
        if: ${{ github.event.inputs.log_errors == 'true' && steps.test_step.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: ./error.log

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to DockerHub
        run: echo ${{ secrets.EMMY_DOCKER_PASSWORD }} | docker login -u ${{ secrets.EMMY_DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push $DOCKER_IMAGE_NAME

