name: Emmy - Fetch Weather Data, Test and Build Docker Image

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Log errors if tests fail"
        required: true
        default: "false"

env:
  DOCKER_IMAGE_NAME: emmynaessrieback/devops_project_emmy

jobs:
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.EMMY_DOCKER_USERNAME }}
          password: ${{ secrets.EMMY_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
